[google_oauth]
client_id = "44089178154-3tfm5sc60qmnc8t5d2p92innn10t3pu3.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://neuronerds.streamlit.app/"
